/* Automatically generated by '../build/build-entry.js' */

import IgtButton from '../packages/igt-button'
import IgtCard from '../packages/igt-card'

const components = [
    IgtButton,
    IgtCard
];

const install = Vue => {
    components.forEach(component =>  {
        Vue.component(component.name, component);
    })
};

export default {
    install,
    IgtButton,
    IgtCard
}
